POST http://localhost:5001/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@example.com",
    "password": "secret123",
    "userName": "johndoe"
}
###

POST http://localhost:5001/login
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "secret123"
}


