POST http://localhost:5001/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@example.com",
    "password": "secret123",
    "userName": "johndoe"
}
###

POST http://localhost:5001/login
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "secret123"
}


GET http://localhost:5001/get_user_and_profile
Content-Type: application/json

{
  "token": "6f7eb945bf6b7cd7866038e3f74e4f842abe8419aa00fc63db1691f4a9f6a564"
}

