POST http://localhost:5001/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@example.com",
    "password": "secret123",
    "userName": "johndoe"
}
###

POST http://localhost:5001/login
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "secret123"
}

#####
POST http://localhost:5001/get_user_and_profile
Content-Type: application/json

{
  "token":"a00c04ec0dec01e3d3c4a979ee1fb8408d9af04dbc9dff74eef7f43c884b0bd8",
  "name": "John Doe",
  "email": "john@example.com",
  "userName": "johndoe",
  "profilePicture":""

}

#####
POST http://localhost:5001/update_profile_data
Content-Type: application/json

{
  "token": "a00c04ec0dec01e3d3c4a979ee1fb8408d9af04dbc9dff74eef7f43c884b0bd8",
  "bio": "Backend"
}
